window.portfolioItems = [
  { src: "assets/portfolio/bridal-makeup-bouquet-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Bouquet-ready bridal glow", alt: "Bride holding bouquet with refined bridal makeup", layout: "feature-card" },
  { src: "assets/portfolio/soft-glam-blonde-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Soft blonde glam", alt: "Soft glam blonde makeup portrait" },
  { src: "assets/portfolio/bridal-hair-updo-01.jpg", category: "hair", label: "Bridal Hair", title: "Textured pearl updo", alt: "Bridal updo with pearl hair details", layout: "tall-card" },
  { src: "assets/portfolio/bridal-portrait-garden-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Garden bridal portrait", alt: "Bride in white gown holding bouquet outdoors" },
  { src: "assets/portfolio/south-asian-bridal-red-01.jpg", category: "south-asian", label: "South Asian Bridal", title: "Red bridal ceremony look", alt: "South Asian bride in red bridal outfit with jewelry", layout: "feature-card" },
  { src: "assets/portfolio/bridal-portrait-seated-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Seated bridal portrait", alt: "Bride seated in white dress with polished bridal styling" },
  { src: "assets/portfolio/bridal-mirror-moment-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Mirror-ready moment", alt: "Bride reflected in mirror during wedding morning" },
  { src: "assets/portfolio/bridal-hair-veil-updo-01.jpg", category: "hair", label: "Bridal Hair", title: "Veil-ready updo", alt: "Bridal updo with veil and hair accessory", layout: "tall-card" },
  { src: "assets/portfolio/bridal-hair-ribbon-half-up-01.jpg", category: "hair", label: "Bridal Hair", title: "Ribbon half-up waves", alt: "Half-up hairstyle with pink ribbon and curls" },
  { src: "assets/portfolio/bridal-hair-low-bun-01.jpg", category: "hair", label: "Bridal Hair", title: "Sleek low bun", alt: "Sleek low bun hairstyle from the back" },
  { src: "assets/portfolio/bridal-hair-hollywood-waves-01.jpg", category: "hair", label: "Bridal Hair", title: "Hollywood waves", alt: "Blonde Hollywood wave bridal hairstyle" },
  { src: "assets/portfolio/bridal-makeup-veil-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Veil and soft glam", alt: "Bride with veil and soft bridal makeup", layout: "feature-card" },
  { src: "assets/portfolio/bridal-hair-ribbon-half-up-02.jpg", category: "hair", label: "Bridal Hair", title: "Romantic ribbon curls", alt: "Long curled half-up hairstyle with ribbon" },
  { src: "assets/portfolio/bridal-makeup-smile-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Natural bridal smile", alt: "Bride smiling with natural bridal makeup" },
  { src: "assets/portfolio/soft-glam-lavender-gown-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Lavender event glam", alt: "Soft glam portrait in lavender gown" },
  { src: "assets/portfolio/soft-glam-garden-portrait-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Garden portrait makeup", alt: "Soft glam garden portrait in lavender dress" },
  { src: "assets/portfolio/soft-glam-pink-eyes-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Pink-toned soft glam", alt: "Soft glam makeup with pink eye detail" },
  { src: "assets/portfolio/bridal-hair-half-up-waves-01.jpg", category: "hair", label: "Bridal Hair", title: "Half-up blonde waves", alt: "Half-up blonde bridal waves from behind" },
  { src: "assets/portfolio/soft-glam-natural-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Natural soft glam", alt: "Natural soft glam makeup portrait" },
  { src: "assets/portfolio/bridal-hair-long-curls-01.jpg", category: "hair", label: "Bridal Hair", title: "Long curled finish", alt: "Long curled bridal hairstyle from behind", layout: "tall-card" },
  { src: "assets/portfolio/bridal-hair-long-curls-02.jpg", category: "hair", label: "Bridal Hair", title: "Dimensional long curls", alt: "Dimensional long curled bridal hair" },
  { src: "assets/portfolio/bridal-hair-sleek-low-bun-01.jpg", category: "hair", label: "Bridal Hair", title: "Polished low bun", alt: "Polished low bun bridal hairstyle" },
  { src: "assets/portfolio/bridal-makeup-blonde-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Blonde bridal glam", alt: "Blonde bride with refined bridal makeup" },
  { src: "assets/portfolio/bridal-portrait-gown-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Gown portrait finish", alt: "Bride in lavender gown with polished makeup" },
  { src: "assets/portfolio/bridal-hair-waterfront-low-bun-01.jpg", category: "hair", label: "Bridal Hair", title: "Waterfront low bun", alt: "Low bun bridal hairstyle by the water" },
  { src: "assets/portfolio/bridal-couple-garden-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Garden couple portrait", alt: "Wedding couple standing together in a garden", layout: "feature-card" },
  { src: "assets/portfolio/bridal-hair-textured-low-bun-01.jpg", category: "hair", label: "Bridal Hair", title: "Soft textured bun", alt: "Soft textured bridal low bun" },
  { src: "assets/portfolio/bridal-hair-sleek-low-bun-02.jpg", category: "hair", label: "Bridal Hair", title: "Classic sleek bun", alt: "Classic sleek bridal low bun" },
  { src: "assets/portfolio/bridal-hair-blonde-waves-01.jpg", category: "hair", label: "Bridal Hair", title: "Blonde wave set", alt: "Long blonde waves styled for an event" },
  { src: "assets/portfolio/bridal-makeup-dark-hair-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Dark hair bridal glam", alt: "Bride with dark hair and bridal makeup" },
  { src: "assets/portfolio/bridal-makeup-soft-bride-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Soft bridal skin finish", alt: "Bride with soft polished bridal makeup" },
  { src: "assets/portfolio/bridal-hair-sleek-low-bun-03.jpg", category: "hair", label: "Bridal Hair", title: "Minimal low bun", alt: "Minimal sleek low bun hairstyle" },
  { src: "assets/portfolio/bridal-makeup-bangs-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Bangs and bridal glow", alt: "Bridal makeup portrait with bangs and tiara" },
  { src: "assets/portfolio/bridal-hair-accessory-bun-01.jpg", category: "hair", label: "Bridal Hair", title: "Accessory low bun", alt: "Bridal low bun with floral hair accessory" },
  { src: "assets/portfolio/soft-glam-purple-gown-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Purple gown glam", alt: "Soft glam portrait in purple gown" },
  { src: "assets/portfolio/bridal-hair-textured-updo-01.jpg", category: "hair", label: "Bridal Hair", title: "Textured romantic updo", alt: "Textured romantic bridal updo" },
  { src: "assets/portfolio/soft-glam-white-blazer-01.jpg", category: "soft-glam", label: "Soft Glam", title: "White blazer event look", alt: "Event makeup portrait in white blazer" },
  { src: "assets/portfolio/soft-glam-white-blazer-closeup-01.jpg", category: "soft-glam", label: "Soft Glam", title: "White blazer close-up", alt: "Close-up of event makeup in white blazer" },
  { src: "assets/portfolio/soft-glam-curls-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Defined curls glam", alt: "Soft glam makeup with defined curls" },
  { src: "assets/portfolio/soft-glam-balcony-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Balcony glam portrait", alt: "Soft glam balcony portrait with dark hair" },
  { src: "assets/portfolio/bridal-hair-accessory-waves-01.jpg", category: "hair", label: "Bridal Hair", title: "Accessory waves", alt: "Bridal waves with hair accessory", layout: "tall-card" },
  { src: "assets/portfolio/bridal-portrait-black-white-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Black and white bridal portrait", alt: "Black and white bridal portrait holding bouquet" },
  { src: "assets/portfolio/bridal-bouquet-portrait-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Bouquet portrait", alt: "Bride holding bouquet with soft bridal makeup" },
  { src: "assets/portfolio/editorial-purple-fashion-01.jpg", category: "editorial", label: "Editorial Photoshoot", title: "Purple fashion editorial", alt: "Editorial fashion makeup in purple outfit", layout: "feature-card" },
  { src: "assets/portfolio/soft-glam-gold-dress-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Gold dress event beauty", alt: "Event beauty look in gold dress" },
  { src: "assets/portfolio/bridal-party-group-01.jpg", category: "bridal", label: "Bridal Makeup", title: "Bridal party group", alt: "Bridal party group photo in sage dresses", layout: "feature-card" },
  { src: "assets/portfolio/bridal-party-group-02.jpg", category: "bridal", label: "Bridal Makeup", title: "Wedding party portrait", alt: "Wedding party portrait in soft green dresses" },
  { src: "assets/portfolio/soft-glam-pearl-closeup-01.jpg", category: "soft-glam", label: "Soft Glam", title: "Pearl close-up glam", alt: "Close-up soft glam makeup with pearl necklace" },
  { src: "assets/portfolio/editorial-orchid-beauty-01.jpg", category: "editorial", label: "Editorial Photoshoot", title: "Orchid beauty editorial", alt: "Editorial beauty portrait with orchid flowers" },
  { src: "assets/portfolio/editorial-purple-fashion-02.jpg", category: "editorial", label: "Editorial Photoshoot", title: "Purple editorial pose", alt: "Purple fashion editorial makeup portrait" },
  { src: "assets/portfolio/editorial-purple-fashion-03.jpg", category: "editorial", label: "Editorial Photoshoot", title: "Purple editorial studio", alt: "Editorial purple fashion studio portrait" },
  { src: "assets/portfolio/editorial-fashion-duo-01.jpg", category: "editorial", label: "Editorial Photoshoot", title: "Fashion duo editorial", alt: "Two models in editorial fashion makeup", layout: "feature-card" },
  { src: "assets/portfolio/editorial-fashion-duo-02.jpg", category: "editorial", label: "Editorial Photoshoot", title: "Bold colour duo", alt: "Editorial duo portrait with bold color styling" }
];
